require: rubocop-rspec

AllCops:
  Exclude:
  - 'db/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 85

Metrics/BlockLength:
  Exclude:
    - 'config/routes/**/*'
    - 'lib/tasks/**/*'
  ExcludedMethods:
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - guard
    - included
    - it
    - let
    - let!
    - scenario
    - setup
    - shared_context
    - shared_examples
    - shared_examples_for
    - transaction

Metrics/LineLength:
  Max: 120
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Max: 66

Rails:
  Enabled: true

RSpec/AnyInstance:
  Exclude:
  - 'spec/models/earthquake_spec.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false
