require: rubocop-rspec

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 85

Metrics/LineLength:
  Max: 120
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Max: 66

AllCops:
  Exclude:
  - 'db/**/*'

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/GuardClause:
  Enabled: false
