require: rubocop-rspec

AllCops:
  Exclude:
  - 'db/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 85

Metrics/LineLength:
  Max: 120
  # Ignores annotate output
  IgnoredPatterns: ['\A# \*\*']
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Max: 66

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false
