default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: earthquake_api_development

test:
  <<: *default
  database: earthquake_api_test
